### ISSUE TITLE
Navigation Issue Cursor position on page item 

### ISSUE THREAD

**Issue by HAfsari** [grlicaa/SearchNavigationMenu#3]
How to cursor position go to 1st item on 
https://drive.google.com/file/d/10JNz_bCB1JtVpf8H3eb7JKcEHpb82QrV/view?usp=sharing

**Comment by grlicaa** [comment]
Is that question or issue ?....
Please open your link to public.

**Comment by HAfsari** [comment]
this is question. 
Link : https://drive.google.com/file/d/10JNz_bCB1JtVpf8H3eb7JKcEHpb82QrV/view?usp=sharing

**Comment by grlicaa** [comment]
Good question now i get it ...... this will be fixed in next release..... 
but for now here is workaround

On page you need focus first item add Dynamic action....
![focus_item](https://user-images.githubusercontent.com/30799807/45376879-3d9d4000-b5f9-11e8-88fa-3d6c49ef8656.png)

Add fixed script file into plugin
[searchNavMenu.zip](https://github.com/grlicaa/SearchNavigationMenu/files/2372068/searchNavMenu.zip)

Unzip first and than 
![focus_upload_file](https://user-images.githubusercontent.com/30799807/45377081-d59b2980-b5f9-11e8-9a45-d380a48588aa.png)

**Comment by HAfsari** [comment]
Tnk. for ur support but stile not working for me

**Comment by grlicaa** [comment]
Can you please provide some test / sample demo application ?
I tested for me works normally on last version of APEX18.1

**Comment by HAfsari** [comment]
https://apex.oracle.com/pls/apex/f?p=25168

User : rbias password : a

**Comment by grlicaa** [comment]
You know that I can't see or do anything without Developer privileges ?
I only sow that you added correct script.

**Comment by HAfsari** [comment]
workspace : menutest user : afsari@mislbd.com pass : a

**Comment by grlicaa** [comment]
Fix it...... 
here is new script... 

[searchNavMenu.zip](https://github.com/grlicaa/SearchNavigationMenu/files/2386483/searchNavMenu.zip)

it was different for dynamic and static navigation list..... now we wait to page set focus first item and than make changes :)....

**Comment by grlicaa** [comment]
Fixed in release 2.1
